import type { Appointment, AuthIdentity, Book } from '../types/app'
import { createCoverDataUrl } from './covers'

export const mockBooks: Book[] = [
  {
    id: 'book-001',
    codigoLivro: 'BGV-0001',
    title: 'Verde Amanhecer',
    author: 'Helena Duarte',
    synopsis:
      'Uma coletânea de memórias da cidade, mesclando literatura regional, encontros na praça e a rotina silenciosa da biblioteca.',
    genre: 'Romance histórico',
    language: 'Português',
    publishedYear: 2024,
    pages: 248,
    totalCopies: 7,
    availableCopies: 4,
    popularityScore: 93,
    featuredRank: 1,
    coverUrl: createCoverDataUrl('Verde Amanhecer', 0),
    createdAt: '2026-06-12T10:00:00.000Z',
  },
  {
    id: 'book-002',
    codigoLivro: 'BGV-0002',
    title: 'Mapa das Chuvas',
    author: 'Caio Nascimento',
    synopsis:
      'Um relato sensível sobre deslocamento, pertencimento e o modo como pequenos lugares guardam histórias imensas.',
    genre: 'Ficção contemporânea',
    language: 'Português',
    publishedYear: 2025,
    pages: 312,
    totalCopies: 5,
    availableCopies: 2,
    popularityScore: 88,
    featuredRank: 2,
    coverUrl: createCoverDataUrl('Mapa das Chuvas', 1),
    createdAt: '2026-06-20T10:00:00.000Z',
  },
  {
    id: 'book-003',
    codigoLivro: 'BGV-0003',
    title: 'A Sala de Leitura',
    author: 'Marina Fagundes',
    synopsis:
      'Entre estantes e cadernos, uma narradora encontra vínculos com a cidade, a escola e os hábitos que mantêm a cultura viva.',
    genre: 'Crônica',
    language: 'Português',
    publishedYear: 2023,
    pages: 184,
    totalCopies: 6,
    availableCopies: 6,
    popularityScore: 81,
    featuredRank: 3,
    coverUrl: createCoverDataUrl('A Sala de Leitura', 2),
    createdAt: '2026-05-30T10:00:00.000Z',
  },
  {
    id: 'book-004',
    codigoLivro: 'BGV-0004',
    title: 'Silêncios do Rio',
    author: 'Rafael Moraes',
    synopsis:
      'Narrativa sobre memória familiar, natureza e o tempo que corre em paralelo ao curso do rio na região sul.',
    genre: 'Drama',
    language: 'Português',
    publishedYear: 2022,
    pages: 276,
    totalCopies: 4,
    availableCopies: 1,
    popularityScore: 96,
    featuredRank: 4,
    coverUrl: createCoverDataUrl('Silêncios do Rio', 3),
    createdAt: '2026-06-22T10:00:00.000Z',
  },
  {
    id: 'book-005',
    codigoLivro: 'BGV-0005',
    title: 'Atlas da Espera',
    author: 'Lia Monteiro',
    synopsis:
      'Ensaios curtos sobre circulação, tempo livre e os rituais cotidianos que transformam uma biblioteca em ponto de encontro.',
    genre: 'Ensaio',
    language: 'Português',
    publishedYear: 2021,
    pages: 220,
    totalCopies: 3,
    availableCopies: 3,
    popularityScore: 79,
    featuredRank: 5,
    coverUrl: createCoverDataUrl('Atlas da Espera', 4),
    createdAt: '2026-06-03T10:00:00.000Z',
  },
  {
    id: 'book-006',
    codigoLivro: 'BGV-0006',
    title: 'O Jardim das Letras',
    author: 'Nina Porto',
    synopsis:
      'Uma obra afetiva sobre infância, leitura e o poder das pequenas cidades para cultivar leitores ao longo do tempo.',
    genre: 'Infantil',
    language: 'Português',
    publishedYear: 2025,
    pages: 96,
    totalCopies: 8,
    availableCopies: 7,
    popularityScore: 84,
    featuredRank: 6,
    coverUrl: createCoverDataUrl('O Jardim das Letras', 0),
    createdAt: '2026-06-26T10:00:00.000Z',
  },
]

export const mockProfile: AuthIdentity = {
  id: 'demo-user',
  email: 'visitante@biblioteca.local',
  fullName: 'Visitante da Biblioteca',
  phone: '(00) 00000-0000',
  avatarUrl: '',
  role: 'reader',
  isDemo: true,
}

export const mockAppointments: Appointment[] = [
  {
    id: 'apt-001',
    scheduledFor: '2026-07-10T15:00:00.000Z',
    status: 'confirmed',
    contactName: 'Visitante da Biblioteca',
    contactPhone: '(00) 00000-0000',
    notes: 'Retirada no balcão principal.',
    createdAt: '2026-07-01T14:00:00.000Z',
    items: [
      {
        id: 'item-001',
        appointmentId: 'apt-001',
        book: {
          id: 'book-001',
          codigoLivro: 'BGV-0001',
          title: 'Verde Amanhecer',
          author: 'Helena Duarte',
          coverUrl: createCoverDataUrl('Verde Amanhecer', 0),
          availableCopies: 4,
          totalCopies: 7,
        },
        position: 1,
      },
    ],
  },
]

